root: true
extends:
  - plugin:markdown/recommended
plugins:
  - markdown
overrides:
  - files: '**/*.md'
    processor: 'markdown/markdown'
rules:
  eol-last: error
  eqeqeq: ["error", "always", { "null": "ignore" }]
  no-console: error
  no-mixed-spaces-and-tabs: error
  no-multiple-empty-lines: ["error", { "max": 1, "maxEOF": 0 }]
  no-path-concat: error
  no-redeclare: ["error", { "builtinGlobals": false }]
  no-trailing-spaces: error
  one-var: ["error", { "initialized": "never" }]
